export const ADD_TRACK = "ADD_TRACK"
export const PLAY_TRACK = "PLAY_TRACK"
export const ACTIVE_TRACK = "ACTIVE_TRACK"
export const SHUFFLE_TRACKS = "SHUFFLE_TRACK"
export const ADD_USER = "ADD_USER"
export const FAVORITES_TRACKS = "FAVORITES_TRACKS"
export const NEXT_AND_PREV_TRACK = "NEXT_AND_PREV_TRACK"
export const ADD_CATEGORY_PLAYLIST = "ADD_CATEGORY_PLAYLIST"

export const SEARCH = "SEARCH"

export const FILTERED_TRACKS = "FILTERED_TRACKS"

export const ARRAY_FITERED_TRACKS = "ARRAY_FITERED_TRACKS"

export const ARRAY_GENRE = "ARRAY_GENRE"
export const ARRAY_YEAR = "ARRAY_YEAR"

export const FLAG_FILTERS = "FLAG_FILTERS"
